### ISSUE TITLE
example on how to start this on every node?

### ISSUE THREAD

**Issue by jchauncey** [fabric8io/docker-fluentd-kubernetes#1]
Obviously daemon controller is the way to go here but have you guys actually tried that yet? Should this work if I use a daemon controller manifest to start it?

**Comment by jimmidyson** [comment]
It certainly should work, haven't had a chance to try.

We currently use a per-node manifest dropped into the manifest file source for the kubelet.

I've seen others hackily use a RC with replicas > nodes (set stupidly high if you want) & use a node port to prevent running multiple replicas on same node.

Whichever way you go, here's a manifest we use which works for us:

``` yaml
apiVersion: v1
kind: Pod
metadata:
  name: fluentd-elasticsearch
spec:
  containers:
  - name: fluentd-elasticsearch
    image: fabric8/fluentd-kubernetes:1.3
    securityContext:
      privileged: true
    resources:
      limits:
        cpu: 100m
    volumeMounts:
    - name: varlog
      mountPath: /var/log
    - name: varlibdockercontainers
      mountPath: /var/lib/docker/containers
      readOnly: true
    env:
    - name: "ES_HOST"
      value: "elasticsearch"
    - name: "ES_PORT"
      value: "9200"
  volumes:
  - name: varlog
    hostPath:
      path: /var/log
  - name: varlibdockercontainers
    hostPath:
      path: /var/lib/docker/containers
```

**Comment by jimmidyson** [comment]
I think you went with the `daemonset` approach? Would you be able to share your manifest that you used?

**Comment by jchauncey** [comment]
Yup I'll post it in a bit.

**Comment by jimmidyson** [comment]
Thanks!

**Comment by jchauncey** [comment]
```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: fluentd-elasticsearch
  labels:
    heritage: helm
    k8s-app: fluentd-elasticsearch
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  template:
    metadata:
      name: fluentd-elasticsearch
      labels:
        heritage: helm
        k8s-app: fluentd-elasticsearch
        version: v1
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - name: fluentd-elasticsearch
        image: fabric8/fluentd-kubernetes:1.3
        securityContext:
          privileged: true
        resources:
          limits:
            cpu: 100m
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        env:
         - name: "ES_HOST"
           value: "elasticsearch-logging"
         - name: "ES_PORT"
           value: "9200"
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
```
